// Generated by https://quicktype.io

export interface Clients {
  success: boolean;
  data: Client[];
}

export interface Client {
  cliente_id: number;
  nombre: string;
  apellido: string;
  direccion: string;
  created_at: null;
  updated_at: null;
}
