// Generated by https://quicktype.io

export interface Quotes {
  success: boolean;
  data: Quote[];
}

export interface Quote {
  cotizacion_id: number;
  cliente_id: number;
  valor: number;
  fecha: string;
  created_at: string;
  updated_at: string;
  cotizacion_producto: CotizacionProducto[];
  cliente: Cliente;
}

export interface Cliente {
  cliente_id: number;
  nombre: string;
  apellido: string;
  direccion: string;
  created_at: null;
  updated_at: null;
}

export interface CotizacionProducto {
  producto_id: number;
  codigo: string;
  nombre: string;
  precio: number;
  imagen: string;
  activo: number;
  created_by: number;
  created_at: null;
  updated_at: null;
  pivot: Pivot;
}

export interface Pivot {
  cotizacion_id: number;
  producto_id: number;
}
